class SlippiActionCounts {
    constructor(actionCounts, playerID) {
        this.airDodge = actionCounts[playerID]["airDodgeCount"];
        this.dashDance = actionCounts[playerID]["dashDanceCount"];
        this.grabFail = actionCounts[playerID]["grabCount"]['fail'];
        this.grabSuccess = actionCounts[playerID]["grabCount"]['success'];
        this.groundTechAway = actionCounts[playerID]["groundTechCount"]['away'];
        this.groundTechIn = actionCounts[playerID]["groundTechCount"]['in'];
        this.groundTechNeutral = actionCounts[playerID]["groundTechCount"]['neutral'];
        this.groundTechFail = actionCounts[playerID]["groundTechCount"]['fail'];
        this.bair = actionCounts[playerID]["attackCount"]["bair"];
        this.dair = actionCounts[playerID]["attackCount"]["dair"];
        this.dash = actionCounts[playerID]["attackCount"]["dash"];
        this.dsmash = actionCounts[playerID]["attackCount"]["dsmash"];
        this.dtilt = actionCounts[playerID]["attackCount"]["dtilt"];
        this.fair = actionCounts[playerID]["attackCount"]["fair"];
        this.fsmash = actionCounts[playerID]["attackCount"]["fsmash"];
        this.ftilt = actionCounts[playerID]["attackCount"]["ftilt"];
        this.jab1 = actionCounts[playerID]["attackCount"]["jab1"];
        this.jab2 = actionCounts[playerID]["attackCount"]["jab2"];
        this.jab3 = actionCounts[playerID]["attackCount"]["jab3"];
        this.jabm = actionCounts[playerID]["attackCount"]["jabm"];
        this.nair = actionCounts[playerID]["attackCount"]["nair"];
        this.uair = actionCounts[playerID]["attackCount"]["uair"];
        this.usmash = actionCounts[playerID]["attackCount"]["usmash"];
        this.utilt = actionCounts[playerID]["attackCount"]["utilt"];
    }
}
module.exports = SlippiActionCounts